#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Ensure servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02

# Update package list and install HAProxy
sudo apt-get -y update
apt-get -y install haproxy

# Set hostnames for web-01 and web-02
# Replace [STUDENT_ID] with your actual student ID (e.g., 6536).

# Set hostname for web-01
ssh ubuntu@35.174.4.60 "sudo hostnamectl set-hostname 6536-web-01"

# Set hostname for web-02
ssh ubuntu@34.230.45.161 "sudo hostnamectl set-hostname 6536-web-02"

# Edit config file
server_config=\
"
frontend http_front
        bind *:80
        mode http
        default_backend http_back
backend http_back
        balance roundrobin
        server 6536-web-01 35.174.4.60:80 check
        server 6536-web-02 34.230.45.161:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
