#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend elvin100s.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 6536-web-01	35.174.4.60	running	
        server 6536-web-02  3.80.200.254
         
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
