#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to have a custom 404 page in Nginx.

# Update the package list and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Allow Nginx HTTP traffic through the firewall
if command -v ufw &> /dev/null; then
    sudo ufw allow 'Nginx HTTP'
else
    echo "UFW is not installed or not available. Skipping UFW configuration."
fi

# Create a custom 404 page
echo "<html>
<head><title>404 Not Found</title></head>
<body>
<h1>404 Not Found</h1>
<p>Get n set pss</p>
</body>
</html>" | sudo tee /var/www/html/custom_404.html > /dev/null

# Configure Nginx to use the custom 404 page
sudo sed -i '/^error_page 404 /d' /etc/nginx/sites-enabled/default
echo "error_page 404 /custom_404.html;" | sudo tee -a /etc/nginx/sites-enabled/default > /dev/null
echo "location = /custom_404.html {" | sudo tee -a /etc/nginx/sites-enabled/default > /dev/null
echo "    internal;" | sudo tee -a /etc/nginx/sites-enabled/default > /dev/null
echo "}" | sudo tee -a /etc/nginx/sites-enabled/default > /dev/null

# Restart Nginx to apply the changes
sudo service nginx restart
