#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to redirect /redirect_me to https://www.github.com/Elvin100s.

# Update the package list and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Allow Nginx HTTP traffic through the firewall
if command -v ufw &> /dev/null; then
    sudo ufw allow 'Nginx HTTP'
else
    echo "UFW is not installed or not available. Skipping UFW configuration."
fi

# Configure Nginx to redirect /redirect_me
sudo sed -i '/^server {/,/^}/ {
    /^server {/a \
    \trewrite ^/redirect_me https://www.github.com/Elvin100s permanent;
}' /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart
